#cloud-config
repo_update: true
repo_upgrade: all

packages:
    - nginx
# write_files:
#     - owner: www-data:www-data
#       path: /etc/nginx/sites-available/default
#       content: |
#           server {
#             listen 80;
#             location / {

#             }
#           }
runcmd:
    # - [sh, 'amazon-linux-extras enable epel']
    # - [sh, 'yum install epel-release -y']
    # - [sh, 'yum install nginx -y']
    - [sh, -c, 'amazon-linux-extras install -y nginx1']
    - systemctl start nginx
