#cloud-config
repo_update: true
repo_upgrade: all

write_files:
  - owner: root:root
    path: /etc/systemd/system/goserver.service
    content: |
      [Unit]
      Description=gowebserver

      [Service]
      Type=simple
      User=ec2-user
      Restart=always
      RestartSec=5s
      ExecStart=/srv/go-server/main

      [Install]
      WantedBy=multi-user.target
  - owner: nginx:nginx
    path: /etc/nginx/conf.d/go_proxy.conf
    content: |
      server {
        listen 80;
        location / {
          proxy_pass http://localhost:8080;
        }
      }
    defer: true
runcmd:
  - mkdir /srv/go-server
  - curl -sLSf https://github.com/derekhassan/terraform-aws-learning/releases/download/v0.4/terraform-aws-learning-v0.4-linux-amd64 > /srv/go-server/main && chmod +x /srv/go-server/main
  - [sh, -c, "amazon-linux-extras install -y nginx1"]
  - service goserver start
  - systemctl start nginx
