#cloud-config
repo_update: true
repo_upgrade: all

write_files:
  - owner: ec2-user:ec2-user
    path: /etc/systemd/system/goserver.service
    content: |
      [Unit]
      Description=gowebserver

      [Service]
      Type=simple
      User=ec2-user
      Restart=always
      RestartSec=5s
      ExecStart=/home/ec2-user/go-server/main

      [Install]
      WantedBy=multi-user.target
  - owner: ec2-user:ec2-user
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80;
        location / {
          proxy_pass http://localhost:8080;
        }
      }
runcmd:
  # - [sh, 'amazon-linux-extras enable epel']
  # - [sh, 'yum install epel-release -y']
  # - [sh, 'yum install nginx -y']
  - mkdir -m777 /home/ec2-user/go-server
  - curl -sLSf https://github.com/derekhassan/terraform-aws-learning/releases/download/v0.3/terraform-aws-learning-v0.3-linux-amd64 > /home/ec2-user/go-server/main
  - chmod +x /home/ec2-user/go-server/main
  - [sh, -c, "amazon-linux-extras install -y nginx1"]
  - service goserver start
  - systemctl start nginx
